lib/protocol/http1/connection.rb, spec/protocol/http1/connection_spec.rb
Although HTTP header values are case-sensitive in general,
RFC 7230 https://tools.ietf.org/html/rfc7230#section-6.1 says:
"Connection options are case-insensitive."
See also:
- https://stackoverflow.com/a/25660341/468618
- The "Connection" example in the MDN Keep-Alive docs:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive
An alternative is to move this logic into to `protocol-http`
gem, but it would have to be specific to the `connection`
header because many other headers are case-sensitive.
If you want it there, the logic would go in the `[]=` method
to avoid having to check in multiple places (`fields`, `each`,
`extract`, `to_h`, `inspect`, `==`).
=> Parse HTTP `connection` header as case-insensitive.

lib/protocol/http1/connection.rb, spec/protocol/http1/connection_spec.rb
Fix a dangerous typo in `Connection` class. `VERSION` evaluates to gem version not HTTP protocol version.
With this correction HTTP11 protocol version is unable to write fixed length bodies. Instead, it defaults to writing chunked bodies (this is covered with a spec).
I don't know if this behavior is desired. If no then maybe we should remove this condition `version != HTTP11`.
=> Fix typo in Connection

lib/protocol/http1/connection.rb, spec/protocol/http1/connection_spec.rb
In https://github.com/socketry/protocol-http1/pull/9 we discussed whether HTTP/1.1 should be allowed to send fixed length body. This PR implements the proposed change. We may need to check if there are unexpected changes downstream (e.g. buffering issues).
cc @bruno-
=> Allow HTTP/1.1 connections to write fixed length bodies.

lib/protocol/http1/body/chunked.rb, lib/protocol/http1/connection.rb, test/protocol/http1/connection.rb, test/protocol/http1/connection/bad.rb
Security researchers @mukeran and @chenjj have reported issues with parsing content length and chunk lengths:
[RFC 9112 Section 7.1](https://www.rfc-editor.org/rfc/rfc9112#name-chunked-transfer-coding) defined the format of chunk size, chunk data and chunk extension (detailed ABNF is in Appendix secion).
In a word:
- The value of Content-Length header should be a string of 0-9 digits.
- The chunk size should be a string of hex digits and should split from chunk data using CRLF.
- The chunk extension shouldn't contain any invisible character.
However, we found that Falcon has following behaviors while disobey the corresponding RFCs.
- Falcon accepts Content-Length header values that have "+" prefix.
- Falcon accepts Content-Length header values that written in hexadecimal with "0x" prefix. …
=> Strict validation of content length and chunk length.

.mailmap, lib/protocol/http1/body/chunked.rb
This PR fixes this warning from ruby 3.2.2:
```
.../protocol-http1-0.15.1/lib/protocol/http1/body/chunked.rb:44: warning: assigned but unused variable - extensions
```
- Maintenance.
=> Fix ruby warning

lib/protocol/http1/connection.rb
This PR allows `connection.persistent = false` to be called externally.
Use cases:
1. Server connections - As part of a more graceful shutdown, I want in-flight connections to be allowed to finish the current request/response, but then terminate and not be reused. In addition to closing the connection, flagging connections in this way allows them to return a `Connection: closed` header so the client is properly notified that this connection isn't to be reused for further requests.
2. Client connections - When certain conditions are met, I want to flag client connections as not eligible to be returned to the Pool for reuse. This could be because the connection configuration has changed, a maximum request count has been reached, etc.
I'm not sure setting `connection.persistent = true` is …
=> Allow persistent=false to be set externally

lib/protocol/http1/connection.rb
This PR splits off reading of the first line of both requests and responses into separate methods. It makes no functional changes.
The intent is to make it easier to inject added functionality after reading the first line (ie: preface) or before reading the headers, most likely via a monkeypatch.
Immediate use case: changing the IO stream timeout before and after reading the preface line.
Related to socketry/async-http#127.
- New feature.
=> Breakout reading of request and response prefaces

lib/protocol/http1/body/remainder.rb, test/protocol/http1/body/remainder.rb
It turns out that for sockets, `eof?` can block. In `empty?` we optimistically care about whether there is data or not, and don't want to block.
See https://bugs.ruby-lang.org/issues/20215 for more context.
- Bug fix.
=> `eof?` can and does block, so let's avoid it.

lib/protocol/http1/connection.rb, test/protocol/http1/hijack.rb
A plain simple `#hijacked?` getter indicating hijack status of the connection. 
This change's ultimate goal is become a part of  https://github.com/socketry/async-http/pull/151.
- New feature.
=> Adding #hijacked? method to connection

lib/protocol/http1/connection.rb
It does not appear guaranteed that `close_write` will flush the underlying IO buffers, so let's ensure it's flushed.
I encountered this problem when implementing `async-http` using native IO.
- Bug fix.
=> Invoke `flush` before `close_write` in `write_body_and_close`.

lib/protocol/http1/connection.rb, test/protocol/http1/connection.rb, test/protocol/http1/hijack.rb
This PR ensures that responses with either 1xx statuses or `Remainder` bodies both set `@persistent = false`.
1xx statuses indicate that the current response is not complete. Similarly, `Remainder` bodies indicate an indeterminate body and thus an inability to know when it is complete. In both cases, this makes it important to mark the client connection as not persistent.
This is required so that `Async::Pool::Controller` will not accidentally attempt to reuse the connection. When determining whether a connection is eligible for reuse, Pool calls `connection.reusable?`, which in turn references `@persistent`.
The choice to modify `@persistent` inside `read_remainder_body` was chosen as it parallels similar behavior in various `write_*` methods. I also considered adding logic to …
=> Ensure 1xx and Remainder responses mark connection as not persistent

lib/protocol/http1/connection.rb, test/protocol/http1/connection.rb, test/protocol/http1/upgrade.rb
For the sake of implementing proxies, it might be nice to map upgrade requests/responses to appropriate bodies. Previously the only mechanism was to hijack the connection, but this makes implementing a generic proxy more complicated.
- New feature.
=> Improve request upgrade body handling.

lib/protocol/http1/connection.rb, test/protocol/http1/connection.rb
In order to prevent some types of invalid usage, and to better track connection reuse, introduce a `@state` variable for the connection and enforce some basic checks on state transitions.
- New feature.
=> State machine tests.

lib/protocol/http1/connection.rb, lib/protocol/http1/error.rb
This prevents request line, response line, or header lines from being too large.
- Security.
=> Add support for maximum line length.

lib/protocol/http1/connection.rb, test/protocol/http1/connection.rb, test/protocol/http1/connection/persistent.rb
`Connection.new(..., persistent: false)` should prevent persistent connections.
- Bug fix.
=> Persistent can only transition from `true` to `false`.

lib/protocol/http1/connection.rb, test/protocol/http1/connection/headers.rb, test/protocol/http1/parser.rb
We identified a specific header format which included tab characters, which was rejected by the existing header parser. This change aligns the header `FIELD_VALUE` to more closely align with <https://www.rfc-editor.org/rfc/rfc7230.html#section-3.2>.
This also prevents headers with non-printable ASCII characters (decimal value 127+), as per the above RFC. This might be considered a breaking change as previously these values were allowed.
- Bug fix.
- Breaking change.
=> Fix header parsing, allowing for \t characters between VCHAR.

lib/protocol/http1/connection.rb, test/protocol/http1/connection/headers.rb
We found header values in the wild containing high bytes. After [surveying the landscape](https://github.com/rack/rack/issues/2308), it seems like the RFC specification is unrealistic.
- Bug fix.
=> Relax header parsing to allow high bytes and most control characters.

lib/protocol/http1/connection.rb, test/protocol/http1/connection/headers.rb
The recent change to the parser prevented empty headers from being sent over the wire by `#write_response`. Fix this regression and add tests.
- Bug fix.
=> Allow empty header values.

lib/protocol/http1/connection.rb, releases.md, test/protocol/http1/connection.rb
Handle missing line termination separately from lines that are too long.
- Maintenance.
=> Better error handling.

lib/protocol/http1/connection.rb, releases.md, test/protocol/http1/connection.rb
If the remote connection abruptly terminates the stream, return `nil` from `read_line?`.
- Bug fix.
=> Ignore connection errors in `read_line?`.
